[package]
name = "hello-aws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.5.8"
aws-sdk-dynamodb = "1.50.0"
tokio = { version = "1.41.0", features = ["full"] }
